apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: nginx-init-container
        image: ubuntu:latest 
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ['sh', '-c', 'echo Hello from $NODE_NAME > /hostname/hostname.html']
        volumeMounts:
        - mountPath: /hostname
          name: mvl
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - mountPath: /hostname
          name: mvl
        - mountPath: /usr/share/nginx/html
          name: mvl
      volumes:
      - name: mvl
        emptyDir: {}
