apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    env:
    volumeMounts:
      - name: mount
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: mount
    configMap:
      name: html-data  
