apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    args:
      #    - /bin/sh
      #    - -c
      #    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      httpGet:
        path: /
        port: 80
        #        httpHeaders:
        #        - name: Custom-Header
        #          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
