apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox 
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/file1 | echo "This is file1" >> file1; sleep 120; rm -f /tmp/file1; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/file1
      initialDelaySeconds: 5
      periodSeconds: 5
